Addition of an array average updater
ammarhakim/gkylzero pull request #558
Opened 2024-12-13 22:15 UTC by Antoinehoff

The `array_average` updater is a new feature designed to compute the DG coefficients of the weighted average of a `gkyl_array` across arbitrary dimensions. It was developed to support the calculation of flux-surface averages in 3x2v clopen simulations, which involves averaging on a surface a 3D field weighted by the configuration space Jacobian (see DR #557 ).

The associated unit test, `ctest_array_average.c`, validates the updater by computing weighted averages for non-trivial functions in 1x, 2x, and 3x cases. It demonstrates the ability to perform sub-dimensional averages and verifies the results by computing the total average through various steps and comparing the result with the `gkyl_array_integrate` updater.

This implementation introduces no changes to existing files in the `gk-g0-app` branch, apart from adding kernel linkage to the Makefile.

### Caveats:
- The updater does not currently support phase-space arrays.
- MPI parallelization has not been tested.

2024-12-18 18:30 UTC, Antoinehoff commented
About handling MPI parallelization:
One could think that computing the local average and then reducing it from all MPI processes would work like it is done for the array_integrate updater. However, the average of local average is not the same as the total average because of the presence of the denominator that must be treated locally.
It is hence mandatory to treat globally at least the integral of the weight (the denominator) when the updater is created.

2025-01-25 00:18 UTC, JunoRavin commented on zero/array_average.c
> +  for (unsigned d=0; d < up->ndim; ++d)
For loops like this, even though braces are not strictly required because the for loop only includes the singular if statement, since the if statement is multiple lines please add braces for the for loop for readability of the loop block. 

Also (this applied everywhere) make sure there is a space between the for loop/if statement and the brace 

for (unsigned d=0; d < up->ndim; ++d) {
}

**not**

for (unsigned d=0; d < up->ndim; ++d){
}

Also, for consistency with everywhere else in the code. Just use int in for loops like this. No need to use unsigned here.

2025-01-25 00:20 UTC, JunoRavin commented on zero/gkyl_array_average.h
> + * Create a new updater that computes the average of a gkyl_array
Can you add a note to this new method that the object is recursive if you are performing a weighted average? In cases where we use these recursively defined objects where you make an array_average_new inside array_average_new when dealing with a weight, I think we should document carefully **why** the object is recursive.

2025-01-25 00:23 UTC, JunoRavin commented
Can we add some documentation to this PR about the types of averaging this will be used for, and potentially even an equation comment in the header file for what the operation is doing? I think it would be useful to have equations both here and in the header for why this averaging operator is unique compared to just giving us the cell average in a cell or integrating cell averages over the whole domain (and thus how it is very useful).

2025-01-27 14:40 UTC, Antoinehoff commented
@JunoRavin I think I assessed your comments, please let me know if you want to see something else be clarified

2025-01-27 14:43 UTC, JunoRavin approved these changes
Ready to merge!

2025-01-28 16:17 UTC, manauref commented
Antoine, in your simulations, is this only working on 1 CPU/GPU? if not, can you point to the code where the reduction over multiple CPUs/GPUs is done?

2025-01-28 16:32 UTC, manauref requested changes
Only minor changes asked for. One additional thing: can you run this unit test on a Perlmutter CPU build with
```
valgrind --leak-check=full ./build/unit/ctest_array_average
```
to make sure it is memory-bug free please?

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +    struct gkyl_array_average_inp inp_avg_full = {
indentation messed up

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("Relative error: %e\n", fabs(result - solution) / fabs(solution));
comment these print statements out. They are useful during dev and debugging, but once the unit test is in place one only want to know if it passes or fails, and not receive numbers on the screen that only make sense to the author.

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\tRelative error: %e\n", rel_err);
see earlier comment about prints

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\tRelative error: %e\n", rel_err );
see earlier comment about prints

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\tRelative error: %e\n", rel_err);
see earlier comment about prints

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\tRelative error: %e\n", rel_err);
see earlier comment about prints

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\tRelative error: %e\n", rel_err);
see earlier comment about prints

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\tRelative error: %e\n", rel_err);
see earlier comment about prints

2025-01-28 16:32 UTC, manauref commented on unit/ctest_array_average.c
> +  printf("\n-X to average, p = %d\n",p);
remove this print statement and the other ones below

2025-01-28 16:32 UTC, manauref commented on zero/array_average.c
> +  // (will be used in advance and in the declaration of the integrated weighted array)
delete these lines. They are unnecessary (or unnecessarily verbose)

2025-01-28 16:32 UTC, manauref commented on zero/gkyl_array_average.h
> + * @param use_gpu       Boolean flag indicating whether the computation should be performed on a GPU.
I used to use spaces like these and got heavily criticized for years. The code doesn't use them, so please remove.

2025-01-28 16:32 UTC, manauref commented on zero/gkyl_array_average_priv.h
> +  gkyl_array_average_cu_dev_new(struct gkyl_array_average *up);
remove indent

also, add a comment saying what these two functions are

2025-01-28 18:18 UTC, Antoinehoff commented
> Antoine, in your simulations, is this only working on 1 CPU/GPU? if not, can you point to the code where the reduction over multiple CPUs/GPUs is done?

I run only 1 GPU simulations when using the array_average. The results of using the array_average to set the limiter bias were not convincing enough to develop multi GPU capability on the phase6 branch.

2025-02-03 19:26 UTC, Antoinehoff commented
Here is the valgrind output of the ctest on perlmutter:
```
==778532== Memcheck, a memory error detector
==778532== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==778532== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==778532== Command: ./build/unit/ctest_array_average
==778532== 
==778573== 
==778573== HEAP SUMMARY:
==778573==     in use at exit: 9,402 bytes in 100 blocks
==778573==   total heap usage: 226 allocs, 126 frees, 117,922 bytes allocated
==778573== 
==778573== 417 (96 direct, 321 indirect) bytes in 1 blocks are definitely lost in loss record 98 of 100
==778573==    at 0x4E056A4: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==778573==    by 0x526C74B: gkyl_malloc_ (alloc.c:46)
==778573==    by 0x517ACA9: array_new (array.c:76)
==778573==    by 0x517ACA9: gkyl_array_new (array.c:130)
==778573==    by 0x404F29: mkarr (ctest_array_average.c:25)
==778573==    by 0x404F29: test_1x (ctest_array_average.c:114)
==778573==    by 0x404F5F: test_1x_cpu (ctest_array_average.c:1072)
==778573==    by 0x403D81: test_do_run_ (acutest.h:1012)
==778573==    by 0x402822: test_run_ (acutest.h:1108)
==778573==    by 0x402822: main (acutest.h:1735)
==778573== 
==778573== 561 (96 direct, 465 indirect) bytes in 1 blocks are definitely lost in loss record 100 of 100
==778573==    at 0x4E056A4: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==778573==    by 0x526C74B: gkyl_malloc_ (alloc.c:46)
==778573==    by 0x517ACA9: array_new (array.c:76)
==778573==    by 0x517ACA9: gkyl_array_new (array.c:130)
==778573==    by 0x404F29: mkarr (ctest_array_average.c:25)
==778573==    by 0x404F29: test_1x (ctest_array_average.c:114)
==778573==    by 0x403D81: test_do_run_ (acutest.h:1012)
==778573==    by 0x402822: test_run_ (acutest.h:1108)
==778573==    by 0x402822: main (acutest.h:1735)
==778573== 
==778573== LEAK SUMMARY:
==778573==    definitely lost: 192 bytes in 2 blocks
==778573==    indirectly lost: 786 bytes in 2 blocks
==778573==      possibly lost: 0 bytes in 0 blocks
==778573==    still reachable: 8,424 bytes in 96 blocks
==778573==         suppressed: 0 bytes in 0 blocks
==778573== Reachable blocks (those to which a pointer was found) are not shown.
==778573== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==778573== 
==778573== For lists of detected and suppressed errors, rerun with: -s
==778573== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
==778575== 
==778575== HEAP SUMMARY:
==778575==     in use at exit: 8,424 bytes in 96 blocks
==778575==   total heap usage: 500 allocs, 404 frees, 265,572 bytes allocated
==778575== 
==778575== LEAK SUMMARY:
==778575==    definitely lost: 0 bytes in 0 blocks
==778575==    indirectly lost: 0 bytes in 0 blocks
==778575==      possibly lost: 0 bytes in 0 blocks
==778575==    still reachable: 8,424 bytes in 96 blocks
==778575==         suppressed: 0 bytes in 0 blocks
==778575== Reachable blocks (those to which a pointer was found) are not shown.
==778575== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==778575== 
==778575== For lists of detected and suppressed errors, rerun with: -s
==778575== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==778580== 
==778580== HEAP SUMMARY:
==778580==     in use at exit: 8,424 bytes in 96 blocks
==778580==   total heap usage: 370 allocs, 274 frees, 1,176,944 bytes allocated
==778580== 
==778580== LEAK SUMMARY:
==778580==    definitely lost: 0 bytes in 0 blocks
==778580==    indirectly lost: 0 bytes in 0 blocks
==778580==      possibly lost: 0 bytes in 0 blocks
==778580==    still reachable: 8,424 bytes in 96 blocks
==778580==         suppressed: 0 bytes in 0 blocks
==778580== Reachable blocks (those to which a pointer was found) are not shown.
==778580== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==778580== 
==778580== For lists of detected and suppressed errors, rerun with: -s
==778580== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==778532== 
==778532== HEAP SUMMARY:
==778532==     in use at exit: 8,376 bytes in 95 blocks
==778532==   total heap usage: 134 allocs, 39 frees, 106,088 bytes allocated
==778532== 
==778532== LEAK SUMMARY:
==778532==    definitely lost: 0 bytes in 0 blocks
==778532==    indirectly lost: 0 bytes in 0 blocks
==778532==      possibly lost: 0 bytes in 0 blocks
==778532==    still reachable: 8,376 bytes in 95 blocks
==778532==         suppressed: 0 bytes in 0 blocks
==778532== Reachable blocks (those to which a pointer was found) are not shown.
==778532== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==778532== 
==778532== For lists of detected and suppressed errors, rerun with: -s
==778532== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2025-02-04 04:23 UTC, manauref commented
> Here is the valgrind output of the ctest on perlmutter:
> 
> ```
> ==778532== Memcheck, a memory error detector
> ==778532== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==778532== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
> ==778532== Command: ./build/unit/ctest_array_average
> ==778532== 
> ==778573== 
> ==778573== HEAP SUMMARY:
> ==778573==     in use at exit: 9,402 bytes in 100 blocks
> ==778573==   total heap usage: 226 allocs, 126 frees, 117,922 bytes allocated
> ==778573== 
> ==778573== 417 (96 direct, 321 indirect) bytes in 1 blocks are definitely lost in loss record 98 of 100
> ==778573==    at 0x4E056A4: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==778573==    by 0x526C74B: gkyl_malloc_ (alloc.c:46)
> ==778573==    by 0x517ACA9: array_new (array.c:76)
> ==778573==    by 0x517ACA9: gkyl_array_new (array.c:130)
> ==778573==    by 0x404F29: mkarr (ctest_array_average.c:25)
> ==778573==    by 0x404F29: test_1x (ctest_array_average.c:114)
> ==778573==    by 0x404F5F: test_1x_cpu (ctest_array_average.c:1072)
> ==778573==    by 0x403D81: test_do_run_ (acutest.h:1012)
> ==778573==    by 0x402822: test_run_ (acutest.h:1108)
> ==778573==    by 0x402822: main (acutest.h:1735)
> ==778573== 
> ==778573== 561 (96 direct, 465 indirect) bytes in 1 blocks are definitely lost in loss record 100 of 100
> ==778573==    at 0x4E056A4: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==778573==    by 0x526C74B: gkyl_malloc_ (alloc.c:46)
> ==778573==    by 0x517ACA9: array_new (array.c:76)
> ==778573==    by 0x517ACA9: gkyl_array_new (array.c:130)
> ==778573==    by 0x404F29: mkarr (ctest_array_average.c:25)
> ==778573==    by 0x404F29: test_1x (ctest_array_average.c:114)
> ==778573==    by 0x403D81: test_do_run_ (acutest.h:1012)
> ==778573==    by 0x402822: test_run_ (acutest.h:1108)
> ==778573==    by 0x402822: main (acutest.h:1735)
> ==778573== 
> ==778573== LEAK SUMMARY:
> ==778573==    definitely lost: 192 bytes in 2 blocks
> ==778573==    indirectly lost: 786 bytes in 2 blocks
> ==778573==      possibly lost: 0 bytes in 0 blocks
> ==778573==    still reachable: 8,424 bytes in 96 blocks
> ==778573==         suppressed: 0 bytes in 0 blocks
> ==778573== Reachable blocks (those to which a pointer was found) are not shown.
> ==778573== To see them, rerun with: --leak-check=full --show-leak-kinds=all
> ==778573== 
> ==778573== For lists of detected and suppressed errors, rerun with: -s
> ==778573== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
> ==778575== 

@Antoinehoff but this is telling you there are two errors in the unit test still, probably because you didn't release those arrays.

2025-02-04 14:42 UTC, manauref approved these changes

2025-02-04 14:42 UTC, merged