Computational to non-uniform mapping for gyrokinetic simulations
ammarhakim/gkylzero pull request #561
Opened 2024-12-20 02:47 UTC by Maxwell-Rosen

Associated DR #546. This has included 8 regression tests in mapc2p, tokamak and mirror geometry. There is a unit test for the zero/position_map.c functionality. Tests have been successfully completed on CPU, GPU, multi-CPU, and multi-GPU. The tests are valgrind clean, although the STEP unit tests are not valgrind clean on gk-g0-app.

Make a non-uniform map with STEP and show how it deforms the map.

Show a WHAM mapping

Cartesian with more cells near z walls (gk-sheath)

2024-12-20 02:53 UTC, Maxwell-Rosen commented on zero/position_map.c
> +  gkyl_array_release(gpm->mc2nu);
Use copy instead of acquire

2024-12-20 18:34 UTC, Maxwell-Rosen commented
Test the root finding map more. Test 2x and 3x wham. Make plots of the magnetic field. Check with a mirror not located at pi/2.

2024-12-30 20:25 UTC, Maxwell-Rosen commented
Here is an example of the non-uniform map working on the STEP geometry to minimize the magnetic field variation.

<img width="670" alt="image" src="https://github.com/user-attachments/assets/d6d40f06-84d2-49c8-b6d4-f59bcd4f2248" />
<img width="670" alt="image" src="https://github.com/user-attachments/assets/cc4175d9-60f3-4f8e-81e8-789aeb43e8dc" />

2024-12-30 20:32 UTC, Maxwell-Rosen commented
Here is a non-uniform map for WHAM that makes dB/dTheta = constant

<img width="670" alt="image" src="https://github.com/user-attachments/assets/3a0b7ff2-761b-4743-bd38-cd03c8d20bd5" />
<img width="670" alt="image" src="https://github.com/user-attachments/assets/5caa4508-b787-4624-8581-0f3f8d4f7331" />

2025-01-06 20:27 UTC, Maxwell-Rosen commented
[Non_uniform_mirror_grids (6).pdf](https://github.com/user-attachments/files/18324165/Non_uniform_mirror_grids.6.pdf)

2025-01-07 16:53 UTC, Maxwell-Rosen commented on zero/gkyl_position_map.h
> +  void *ctx_z;  // Context for map_z.
So in code, this would look something like this
```
mc2nu_t *maps[3]; 
void *ctx[3];
```
A user would set
```
.geometry = {
      .position_map_info = {
        .id = GKYL_PMAP_FUNC,
        .maps = { NULL, NULL, nonuniform_position_map_z},
        .ctx =     { NULL, NULL, ctx},
      },
}
```

2025-01-07 17:07 UTC, manauref commented on zero/gkyl_position_map.h
> +  void *ctx_z;  // Context for map_z.
That's right.

2025-01-09 20:09 UTC, ammarhakim requested changes
Please do not use the keyword NULL. Use 0 instead. Also, use array of function pointers in the proper way.

2025-01-10 16:38 UTC, JunoRavin commented
Summarizing an offline conversation between @Maxwell-Rosen and I:

General feedback: since we always order the coordinates as (position space, velocity space) (position space is first in the coordinate ordering) everywhere you need both the configuration space and velocity space mappings, or include both headers, or specify both structs, let’s order things such that the position space map is passed/acted on first. So for example in the phase mapping function in gk_species_projection.c, evaluate the position_map function first, and then the velocity_map function. This way, we can keep our natural coordinate orderings everywhere (and no future developer wonders if there’s a reason the velocity map is being acted upon first).

2025-01-10 21:13 UTC, Maxwell-Rosen commented
Summarizing another conversation with Jimmy offline, I have been allocating and freeing the global bmag inside the geometry generation, which seems out of place. I implemented it this way because I had been using whether the global bag inside position_map was allocated to determine whether we should do the geometry-dependent optimization inside position_map. Instead, these objects should be allocated inside the position map, and a flag can be set whether we should optimize.

Jimmy also notes that this operation is repeated across many different geometry types, and code is being copied. The geometry generation in gyrokinetic.c could be packaged and moved somewhere else to make it more compact and readable. This is left to future work but is worth revisiting.

2025-01-13 06:09 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +  double *xp = malloc(3*sizeof(double));
here and line 49 below, please don't use malloc for small arrays whose size is known at compile time. Just use double xp[3].

2025-01-13 06:11 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +  int n_ct = app->map_order_center;//app->mapping_order_center;
there's some commented code here. Remove if not needed.

2025-01-13 06:13 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +  // Notation: I switch from theta to z here. Both are computational coordinate.
The reader doesn't know who "I" is. Either speak in 3rd person or initialize and date your comment, e.g. MR 2024/12/25.

2025-01-13 06:14 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +  double *fout = malloc(3*sizeof(double));
don't use mallocs, see earlier comment

2025-01-13 06:16 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +{
add comment describing what this function does.

2025-01-13 06:16 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +calculate_mirror_throat_location_polynomial(struct gkyl_position_map_const_B_ctx *constB_ctx, struct gkyl_bmag_ctx *bmag_ctx)
add comment describing what this function does.

2025-01-13 06:19 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +  double h = 1e-6;
why 1e-6? should this be multiplied by something else? what if my field line is 2e-6 long?

2025-01-13 06:19 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +calc_bmag_global_derivative(double xn, void *ctx)
add comment describing what this function does.

2025-01-13 06:20 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +{
add comment describing what this function does.

2025-01-13 06:20 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +position_map_numeric_optimization_function(double theta, void *ctx)
add comment describing what this function does.

2025-01-13 06:20 UTC, manauref commented on zero/gkyl_position_map_priv.h
> +position_map_constB_z_numeric(double t, const double *xn, double *fout, void *ctx)
add comment describing what this function does.

2025-01-13 17:36 UTC, manauref requested changes

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_calc_bmag.h
> +struct gkyl_bmag_ctx{
Add a comment describing that this struct is for, and each of its contents.

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_calc_bmag.h
> +   const struct gkyl_array* bmag;
what's the difference between these two?

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_gk_geometry.h
> +  struct gkyl_array* mc2nu_pos; // 3 components. Computational to field aligned mapping
shouldn't this comment be "computational to nonuniform" ?

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_gk_geometry.h
> +  struct gkyl_comm *comm; // communicator object
I don't think this is right. Instead of storing a pointer to comm, why can't you pass comm to the respective functions as an argument? we don't store comm anywhere (in zero), and parallel operations are technically always orchestrated at the app level, not at this level.

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_gk_geometry_mirror.h
> + * Wrapper for gkyl_gk_geometry_mirror_advance, neccisary for the non-uniform grids
This added comment seems misleading. Isn't this used/needed if we are not using nonuniform grids? To call it a wrapper for nonuniform grids seems wrong.

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_mirror_geo.h
> +  struct gkyl_mirror_geo *geo, struct gkyl_mirror_geo_grid_inp *inp,
here and elsewhere: update comment with description of new arguments.

2025-01-13 17:36 UTC, manauref commented on zero/gkyl_tok_geo.h
> + * @param position_map position map object
update comment with new arguments.

2025-01-13 17:51 UTC, Maxwell-Rosen commented on zero/gkyl_calc_bmag.h
> +   const struct gkyl_array* bmag;
@akashukla bmagdg is the RZ representation of bmag from the efit file and bmag is in computational coordinates. They are both DG arrays. I find this naming also bad. It should be bmag_rz or something.

2025-01-13 17:56 UTC, Maxwell-Rosen commented on zero/gkyl_gk_geometry.h
> +  struct gkyl_comm *comm; // communicator object
It's because this struct `gkyl_gk_geometry_inp` is the input to all the `gkyl_geometry_new` functions in `gyrokinetic.c`. The only input is this struct. Rather than making many arguments, I pass it this way. It makes the input more flexible also.

This comm is used for the bmag allgather to make bmag global. This operation happens at the zero level because it's in geometry.

2025-01-13 18:00 UTC, Maxwell-Rosen commented on zero/gkyl_mirror_geo.h
> +  struct gkyl_mirror_geo *geo, struct gkyl_mirror_geo_grid_inp *inp,
This must have gotten screwed up by the recent merge

2025-01-14 13:49 UTC, JunoRavin commented on zero/gkyl_gk_geometry.h
> +  struct gkyl_comm *comm; // communicator object
We do sometimes store comm in zero-level objects depending on what parallel operations need to be done at the zero level, such as here in wave_prop.c because it's a single step method that must do the allreduce internally for what the stable time step is: https://github.com/ammarhakim/gkylzero/blob/gk-g0-app/zero/wave_prop.c#L29

So in principal there is no issue with the comm being an internal object of a zero-level struct. So long as things are still done with acquires and releases so the memory is tracked carefully.

2025-01-14 13:54 UTC, JunoRavin commented
@Maxwell-Rosen In looking over your responses to @manauref's comments I realized something else: please give all the small functions defined in the private header the static keyword. Private headers (usually) need to have static functions in case the private header is included multiple places so that the compiler doesn't think there are duplicate symbols (this issue shows up a lot on GPUs when both a .c and .cu file need to include the private header; although there is no position_map_cu.cu function, I think we should institute a discipline that these sorts of private header functions are static).

2025-01-14 16:34 UTC, manauref requested changes
This is very good work Max. Thank you for undertaking this.

I added relatively small comments throughout. I only have 2 more requests before merging:
1. Check that 6 regression tests are valgrind clean, a tokamak one, a mapc2p one, and a mirror one, each with uniform and nonuniform grid. Running them for 3 time steps is sufficient.
2. Work with @pcagas and others to make sure we can plot data from a sim with nonuniform configuration space, and show the corresponding pgkyl command here (like we did in PR #359 ). Otherwise we are introducing huge changes that we cannot use effectively (i.e. to obtain AND convey better results).

I'll do a couple more checks myself too.

2025-01-14 16:34 UTC, manauref commented on zero/position_map.c
> +    gpm->constB_ctx->ctxs_backup[i] = 0;
what are these backups used for? can they be removed? if they are needed in optimization of the map, can't these pointers just be defined locally/temporarily in the optimization funciton?

2025-01-14 16:34 UTC, manauref commented on zero/position_map.c
> +      for (int i = 0; i < 2; i++){
Why is there a 2 here (and in line 66) but there's a 3 in line 47?

2025-01-14 16:34 UTC, manauref commented on zero/gkyl_position_map.h
> +  mc2nu_t maps[3]; // Position mapping in each position direction.
here or somewhere else you must make it clear to the user that even if it's a 1x or 2x sim they must provide a map in all 3 computational coordinate directions, unless a uniform map is desired. Otherwise some people might be confused to see .map[2] = ... in a 1x input file, or they may incorrectly set .map[0] in a 1x input file. This was a common error in the early days of geometry, so let's avoid that this time.

2025-01-14 16:36 UTC, Maxwell-Rosen commented on zero/position_map.c
> +    gpm->constB_ctx->ctxs_backup[i] = 0;
The backups are used for if you want to use a user-defined position map in x and/or y, but a magnetic field dependent map in z. We need a backup because we need to generate the geometry twice. The first time needs uniform everything, but the second time we need non-uniform everything.

2025-01-14 16:38 UTC, Maxwell-Rosen commented on zero/position_map.c
> +      for (int i = 0; i < 2; i++){
Only the 0 and 1 indices are used for the backup because the 2nd index is used with the magnetic field dependent map, so only those 2 parts need to be assigned.

2025-01-14 16:39 UTC, Maxwell-Rosen commented on zero/gkyl_position_map.h
> +  mc2nu_t maps[3]; // Position mapping in each position direction.
In my regression tests, I specify .map[2] = function. This works just fine in my implementation because they are all initialized to identity maps and only assigned if the user gives a function. I should add a comment that they have to specify the position in 3x rather than the deflated geometry

2025-01-14 18:54 UTC, ammarhakim approved these changes

2025-01-14 20:09 UTC, JunoRavin approved these changes

2025-01-14 20:14 UTC, merged

2025-01-15 18:55 UTC, manauref commented
I believe this PR changed the evolution of the field in rt_gk_step_out_2x2v_p1, see below:
![image](https://github.com/user-attachments/assets/c9b0d54b-b0c4-4315-9570-651818dfb833)